import { Tribe } from "./types";

export const tribeAuntiePattysPies: Tribe = {
  name: "Auntie Patty's Pies",
  owner: "Patty",
  percentAngry: 0,
  priceVariability: 5,
  insults: [
          "Quick thing, our town runs a little stamp challenge for traveling parties. It’s meant to keep groups working together instead of talking past each other. Before you lock in a plan, ask one of your companions what they want to do next or what part they want to take.  |  Stamp Quest (Ask First): Before making a plan, ask another PC what they want to do next or what they want to do for their part in the plan. | Reward: 3 Stamps",
          "Since you look like the capable sort, I’ll share one of our stamp challenges. It rewards teamwork over heroics. Next time trouble starts, set up a simple two-person combo with a companion, nothing fancy, just coordinated.  |  Stamp Quest (Tag-Team): Coordinate a 2-person combo in combat (grapple + shove, distraction + sneak, buff + big hit, etc.). | Reward: 5 Stamps",
          "I’ve got a small stamp challenge that’s been good for keeping parties sharp and in sync. When a companion offers an idea, don’t just agree, add to it. Build on what they said and keep the momentum going.  |  Stamp Quest (Yes, And): Say 'Yes, and-' (or the spirit of it) to another player’s idea and build on it. | Reward: 3 Stamps",
          "Alright, here’s a fun little stamp challenge purely for morale. Pick a light accent or a harmless speech quirk and use it in a couple of conversations  |  Stamp Quest (Tiny Accent): Use a very light accent or speech quirk for two separate conversations. If the DM calls it out, fail. | Reward: 3 Stamps",
          "Hello, dearie. I'm sorry for not being at the door when you came in; these old bones aren't what they used to be. Just give me a moment, and I'll be right there!",
          "I'm so sorry—you look just like my grandkid. Say, are you single? I think you two might make a good couple.",
          "Welcome to my little pie shop, every day we have a new granny come and bake a new pie for us to try!",
          "Oh, please don't rob us; the shop right by has way better—oh, sorry. We were robbed a little while ago; guess we're still on edge. Sorry, dearie—how can I help you?",
          "Sometimes we take the pies that are about to expire and hand them out to the crows out back. And sometimes the crows beat up storks and bring us the swaddled babies. I guess that's one way to get grandkids.",
          "Oh my, look how big and strong you are! Say, I could use a good pair of hands like yours. I've got a recipe I've been dying to try! If you'll come in the back, we can get started. All I need from you is a DC 14 Acrobatics check to roll out this dough. If you succeed, I’ll pay you 25 gp. If you fail, you take 1 point of fire damage and I'll pay you 5 gp for your trouble.",

          "Hello, dearie. I'm sorry for not being at the door when you came in; these old bones aren't what they used to be. Just give me a moment, and I'll be right there!",
          "I'm so sorry—you look just like my grandkid. Say, are you single? I think you two might make a good couple.",
          "Welcome to my little pie shop, every day we have a new granny come and bake a new pie for us to try!",
          "Oh, please don't rob us; the shop right by has way better—oh, sorry. We were robbed a little while ago; guess we're still on edge. Sorry, dearie—how can I help you?",
          "Sometimes we take the pies that are about to expire and hand them out to the crows out back. And sometimes the crows beat up storks and bring us the swaddled babies. I guess that's one way to get grandkids.",
          "Hello, dearie. I'm sorry for not being at the door when you came in; these old bones aren't what they used to be. Just give me a moment, and I'll be right there!",
          "I'm so sorry—you look just like my grandkid. Say, are you single? I think you two might make a good couple.",
          "Welcome to my little pie shop, every day we have a new granny come and bake a new pie for us to try!",
          "Oh, please don't rob us; the shop right by has way better—oh, sorry. We were robbed a little while ago; guess we're still on edge. Sorry, dearie—how can I help you?",
          "Sometimes we take the pies that are about to expire and hand them out to the crows out back. And sometimes the crows beat up storks and bring us the swaddled babies. I guess that's one way to get grandkids.",
          "Hello, dearie. I'm sorry for not being at the door when you came in; these old bones aren't what they used to be. Just give me a moment, and I'll be right there!",
          "I'm so sorry—you look just like my grandkid. Say, are you single? I think you two might make a good couple.",
          "Welcome to my little pie shop, every day we have a new granny come and bake a new pie for us to try!",
          "Oh, please don't rob us; the shop right by has way better—oh, sorry. We were robbed a little while ago; guess we're still on edge. Sorry, dearie—how can I help you?",
          "Sometimes we take the pies that are about to expire and hand them out to the crows out back. And sometimes the crows beat up storks and bring us the swaddled babies. I guess that's one way to get grandkids.",
          
          ],
  items: [
    {
      name: "Salted Honey Chess Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Rich, dense, and golden with salted honey-brown-butter vibes; one slice worth a whole meal.",
    },
    {
      name: "Sour-Face Lemon Cream Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Bright, tart lemon cream in a buttery crust sharp enough to make the toughest mercenary blink.",
    },
    {
      name: "Spiced Carrot & Ginger Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "A cozy blend of carrot, ginger, and warm spices sweet without being sugary, with a little zing at the end.",
    },
    {
      name: "Roadwarden Hand Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "A rugged meat-and-root-veg pie baked to survive saddlebags and long roads; hearty and mess-free.",
    },
    {
      name: "Market Sweep Berry Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "A rotating mix of whatever berries were best that morning; every pie is slightly different and always gone by dusk.",
    },
    {
      name: "Cinnamon-Pear Crumble Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Juicy pears under a crunchy cinnamon crumble top; smells like autumn even in midsummer.",
    },
    {
      name: "Smoked Apple & Cheddar Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Sweet apples and sharp cheddar with a whisper of smoke odd on paper.",
    },
    {
      name: "Maple Pecan Slab Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Maple-sweet pecan filling baked firm for clean cuts and easy packing popular with caravans and couriers.",
    },
    {
      name: "Cherry-Almond Lattice Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Tart cherries and almond fragrance beneath a pretty lattice bought as gifts, bribes, and peace offerings.",
    },
    {
      name: "Campfire Chicken Pot Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Flaky crust, thick peppered gravy, and tender chicken comfort food that tastes like a warm campfire story.",
    },
    {
      name: "Don't Tell the Cleric Chocolate Silk Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Dark, silky chocolate custard in a crisp crust decadent enough to inspire minor confessions.",
    },
    {
      name: "Pumpkin Pie of Warmth",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Keeps the eater comfortably warm, warding off natural cold for two hours.",
    },
    {
      name: "Pear Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Increases walking speed by 5 ft until your next rest; non-stackable.",
    },
    {
      name: "Goblin Berry Tart",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "Grants advantage on your next Stealth check.",
    },
    {
      name: "Blueberry Pie of Night Vision",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "Gives darkvision for two hours.",
    },
    {
      name: "Mushroom & Leek Galette",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "Rustic open-face savory pie with buttery mushrooms and leeks; simple, elegant, and shockingly filling.",
    },
    {
      name: "Strawberry Pie of Friendship",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "Eating a slice gives a +1 bonus to Animal Handling checks for one hour.",
    },
    {
      name: "Bead of Nourishment",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "This spongy, flavorless, gelatinous bead dissolves on your tongue and provides as much nourishment as 1 day of rations.",
    },
    {
      name: "Chest of Preserving",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "This common wondrous item has the following magical property: food and other perishable items do not age or decay while inside it. The chest is 2½ feet long, 1½ feet wide and 1 foot tall with a half barrel lid. It weighs 25 pounds.",
    },
    {
      name: "Heward's Handy Spice Pouch",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "This belt pouch appears empty and has 10 charges. While holding the pouch, you can use an action to expend 1 of its charges, speak the name of any nonmagical food seasoning (such as salt, pepper, saffron, or cilantro), and remove a pinch of the desired seasoning from the pouch. A pinch is enough to season a single meal. The pouch regains 1d6 + 4 expended charges daily at dawn.",
    },
    {
      name: "Medal of the Meat Pie",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: `You gain 2d4 + 2 temporary hit points when you use an action to press this medal to your mouth. Once this property has been used, it can’t be used again, and the medal becomes nonmagical.
While magical, this medal is slightly warm to the touch (as if it’s fresh from the oven) and smells faintly of baked pie crust.`,
    },
    {
      name: "Bag Of Bounty",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: `This is a sturdy leather sack with tiny Siberys shards embedded into the lining. If you have the Mark of Hospitality you can use an action to cast Create Food and Water, drawing a feast from within the bag. You shape this meal with your thoughts. You can create the standard bland fare without requiring any sort of check, but you can attempt to create finer food by making a Charisma check; if you’re proficient with cook’s utensils, add your bonus to this check. A failed check results in a sour and squalid meal.
Food Quality | Difficulty
Poor | No roll required
Modest | 10
Comfortable | 13
Wealthy | 15
Aristocratic | 18
A bag of bounty can be used up to three times over the course of a day. After that, the bag can’t be used again until the next dawn.`,
    },
    {
      name: "Dust of Deliciousness",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "This reddish brown dust can be sprinkled over any edible substance to greatly improve the flavor. The dust also dulls the eater's senses: anyone eating food treated with this dust has disadvantage on Wisdom ability checks and Wisdom saving throws for 1 hour. There is enough dust to flavor six servings.",
    },
    {
      name: "Goggles of Night",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "While wearing these dark lenses, you have darkvision out to a range of 60 feet. If you already have darkvision, wearing the goggles increases its range by 60 feet.",
    }
  ],
};
