import { Tribe } from "./types";
import { createGoblinExcuses } from "./tribeInsults";

export const tribe2: Tribe = {
  name: "Grubcar Clan",
  percentAngry: 20,
  priceVariability: 81,
  insults: createGoblinExcuses("Grubcar Clan"),

  items: [
    {
      name: "Terrible Seasonal Cookie Thief",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "(Santa's hat.)",
    },
    {
      name: "Waste of Good Napkin",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(A coupon that offers 25% off your next purchase anywhere; valid for one use only.)",
    },
    {
      name: "Snack?",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Some thrown-out food found in a dumpster, heals 6d4 + the knowledge of eating trash.)",
    },
    {
      name: "Goblin Hand Sanitizer",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(An unopened jar of peanut butter, heals 2d6.)",
    },
    {
      name: "Dino!",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Dinosaur nuggets with your choice of dipping sauce, heals 6d6.)",
    },
    {
      name: "Disappointment",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(A batch of perfectly baked cookies, but the goblins don't have any milk to go with them. Each cookie heals for 5 HP.)",
    },
    {
      name: "Soup?",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(A soggy bowl of cereal, heals 2d8.)",
    },
    {
      name: "Doctor Be GONE!",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(A shiny red apple that regenerates after half of it is gone. Each bite is an action and heals for 1 HP.)",
    },
    {
      name: "Hobo Gum",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(A rock, small enough to chew on.)",
    },
    {
      name: "The One True Enemy",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(A bar of soap, with a bite taken out of it?)",
    },
    {
      name: "Holly's Grail",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(A fresh Costco rotisserie chicken, probably stolen from a person named Holly because her receipt is still in the bag. Heals for 6d12.)",
    },
    {
      name: "No no no I'm your brother! Remember we used to laugh and play down by the river, and Mom would always make us a sandwich when we came inside covered in mud!",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Potion of Forget-Me-Not. After drinking this potion, you will be forgotten by everyone who knows you, unless they have psionic or psychic immunity or resistance.)",
    },
    {
      name: "Liquid Golden Cat Eyes",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "A semi-permanent potion of Darkvision up to 120 feet. However, after drinking and while in darkness, your eyes shift from their original color to a golden yellow, and your pupils stretch, giving them a slitted, cat-like appearance.",
    },
    {
      name: "You really hurt my feelings, why would you do that!",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Liar's Breath, after drinking this potion you gain a +10 to all Deception rolls; however, you are also unable to answer truthfully to any question. The effects of this potion last for 5 hours.)",
    },
    {
      name: "Garbage Crown!",
      rarity: "Rare",
      itemType: "Wondrous Item",
      attunment: false,
      price: 1000,
      description: "(A Burger King crown that will stay on your head until you take it off.)",
    },
    {
      name: "Sekolahian Worshipping Statuette",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "Skillfully carved from sandstone, this 1-foot-tall statuette depicts a shark twisting through the water with its mouth open. If any Tiny sea-dwelling animal is within 1 inch of the statuette's mouth, the shark flashes to life and deals 1 piercing damage to it. The shark can deal damage in this way no more than once per hour.",
    },
    {
      name: "Cap of Water Breathing",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "While wearing this cap underwater, you can speak its command word as an action to create a bubble of air around your head. It allows you to breathe normally underwater. This bubble stays with you until you speak the command word again, the cap is removed, or you are no longer underwater.",
    },
    {
      name: "Decanter of Endless Water",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: `This stoppered flask sloshes when shaken, as if it contains water. The decanter weighs 2 pounds.
You can use an action to remove the stopper and speak one of three command words, whereupon an amount of fresh water or salt water (your choice) pours out of the flask. The water stops pouring out at the start of your next turn. Choose from the following options:
-"Stream" produces 1 gallon of water.
-"Fountain" produces 5 gallons of water.
-"Geyser" produces 30 gallons of water that gushes forth in a geyser 30 feet long and 1 foot wide. As a bonus action while holding the decanter, you can aim the geyser at a creature you can see within 30 feet of you. The target must succeed on a DC 13 Strength saving throw or take 1d4 bludgeoning damage and fall prone. Instead of a creature, you can target an object that isn't being worn or carried and that weighs no more than 200 pounds. The object is either knocked over or pushed up to 15 feet away from you.`,
    },
    {
      name: "Horseshoes of a Zephyr",
      rarity: "Very Rare",
      itemType: "Wondrous Item",
      attunment: false,
      price: 2500,
      description: "These iron horseshoes come in a set of four. While all four shoes are affixed to the hooves of a horse or similar creature, they allow the creature to move normally while floating 4 inches above the ground. This effect means the creature can cross or stand above nonsolid or unstable surfaces, such as water or lava. The creature leaves no tracks and ignores difficult terrain. In addition, the creature can move at normal speed for up to 12 hours a day without suffering exhaustion from a forced march.",
    },
    {
          name: "Last Week's Fish Trip",
          price: 110,
          description: "(Six left boots, three fish, one fishing pole with a pair of pants on the hook, and a tombstone.)",
        }
  ],
};
