import { Tribe } from "./types";
import { createGoblinExcuses } from "./tribeInsults";

export const tribe7: Tribe = {
  name: "Council of Conductors",
  percentAngry: 1,
  priceVariability: 30,
  insults: createGoblinExcuses("The Council of Conductors"),
  items: [
    {
      name: "Creepy bone hand, good for picking an ear though.",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "(Omega Skeleton Key: can unlock any door if the door has a lock. It does not work on any other kind of lock.)",
    },
    {
      name: "A really handy hat",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "(Wander's Hat: whenever you reach into this hat, you have a one-in-three chance of withdrawing a useful item, a detrimental item, or a clue for your current quest.)",
    },
    {
      name: "Sphere of bringing fun friends.",
      rarity: "Uncommon",
      itemType: "Ring",
      attunment: false,
      price: 250,
      description: "(Orb of Summoning, Perform a ten-minute ritual to bring forth... something? What's your alignment again?)",
    },
    {
      name: "OH NO THEY'RE BACK AGAIN, GET THE BREAD! GET THE BREAD!!!",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Tiny Duck Crown: while playing an instrument, roll 3d100. That many rubber ducks spill from your pockets—or real ducks appear. They disappear when you stop playing.)",
    },
    {
      name: "Cut in line, na-na-na boo-boo.",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Quick Swap Ring: swap places with someone within 200 feet once per day.)",
    },
    {
      name: "Neck rope of ghost summoning",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Necklace of Shattered Ages: spinning the gem on the necklace allows the user to see past events that happened nearby.)",
    },
    {
      name: "Derpy lucky charm",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Gateway Amulet: create a portal that lasts five minutes to someone you know who is also wearing a Gateway Amulet. It can be used twice per long rest.)",
    },
    {
      name: "Peabrain page holder ate my cookbook!",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Insatiable Tome: this book eats other books. Ask it a question, and it responds if it consumed a book with the answer you're looking for. Also contains some goblin cooking recipes.)",
    },
    {
      name: "Nice elf lady's book.",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Adel's Old Monster Journal: a journal explaining many monsters Adel encountered on her past adventures.)",
    },
    {
      name: "Eww, gross—I don't want to touch it.",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "Odin's Glass Eye, Warning, your character has to remove one of their functioning eyes for this item to work! You can now summon two ravens of which you can see through their eyes, however if one of the ravens dies so does the other. Ravens can be summoned once per long rest.",
    },
    {
      name: "Kind dwarf's odd box.",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "Pat's Homemade Cottage Chest, Placing this small box on the ground will allow it to open, granting you access to a tiny, cozy-dimension place akin to being inside an authentic cabin. The chest can't be moved if there's a living being inside, but the chest can be destroyed. Where upon any living inside the chest being will be teleported to a safe place from the destruction.",
    },
    {
      name: "The dishonorable & malicious tiara of Solanine the goblin queen.",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "Goblin Warlord's Crown, All goblins within ten miles of the wearer have to obey their commands, if they can hear and understand it. Only three commands can be active at any given time with the oldest command being erased.",
    },
    {
      name: "The forbidden tissue.",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Keoki's All or Nothing Scratch ticket",
    },
    {
      name: "Hands-on goblin learning—they may rough you up a bit, though.",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Skill training: gain proficiency in a skill of your choosing. If you already have proficiency in that skill, it becomes expertise.)",
    },
    {
      name: "Not the kidnap— I mean a normal bag.",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Used Bag of Holding: this is a bag of holding; however, some items you withdraw may have a bit of glitter on them. It may have some other items in there.)",
    },
    {
      name: "SNOW BALL FIGHT! But it's the middle of summer? SNOW BALL FIGHT!",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Ring of Replenishing Snowballs: create and throw up to five harmless snowballs a day—they always hit.)",
    },
    {
          name: "Some terrible cards.",
          price: 1000000,
          description: "(It's the Deck of Many Things & Many Fates, but the goblins may have shuffled them together and aren't too willing to go back and sort it out.)",
        }
  ],
};
