import { Tribe } from "./types";

export const tribeRobinsRopes: Tribe = {
  name: "Robin's Ropes",
  owner: "Robin",
  percentAngry: 0,
  priceVariability: 0,
  insults: [
          "Hey, between you and me, I run a little stamp challenge for regulars. Nothing dangerous, just a bit of fun to keep the road lively.  |  Stamp Quest (Wild Animal): Subtly make animal sounds into conversations, loud enough for the person beside you to hear you, but if you get caught by the ‘DM’, you fail this quest. | Reward: At the session's end, earn stamps equal to the number of animal sounds you successfully make.",
          "I like adventurers who travel as a team, not a parade. Here’s a small stamp challenge I hand out to folks I’m rooting for. Next time, you could take charge, pass the lead to someone else and let them shine.  |  Stamp Quest (Share the Spotlight): When you could take the lead, deliberately hand it to another PC (“You’re better at this than me, you take it.”). | Reward: 4 Stamps",
          "Most people come in here looking for gear, but the smart ones invest in their companions. I’ve got a stamp challenge for that kind of traveler. Help one of your party members make real progress on something personal they’re chasing this session.  |  Stamp Quest (Helping Hand): Help another party member with their personal goal this session. | Reward: 10 Stamps",
          "I don’t like seeing heroes go without when their friends could help. So here’s a little stamp challenge, nice and simple. If a companion’s talking about buying something helpful, surprise them by covering it or gifting them something valuable.  |  Stamp Quest (It’s dangerous to go alone): Give another party member a useful item like a potion, weapon, armor, or a few coins when they are talking about buying an item. | Reward: 3 Stamps",
          "Hello, governor! How are you doing today!",
          "Oi, you interested in ropes now? Well have I got the shop for you!",
          "It ain't much but it's honest work.",
          "Know any good rope jokes? I'm a frayed knot.",
          "A rope and a string got in a race. They tied.",
          "You want to make some quick cash, yah? Come over here and I'll show you how to weave together some rope, ok? Make a DC 14 Sleight of Hand check to help me tie these together. If you succeed, I’ll pay you 25 gp. If you fail, you take 1 point of damage from getting tangled up but still get 5 gp.",

          "Hello, governor! How are you doing today!",
          "Oi, you interested in ropes now? Well have I got the shop for you!",
          "It ain't much but it's honest work.",
          "Know any good rope jokes? I'm a frayed knot.",
          "A rope and a string got in a race. They tied.",
          "Hello, governor! How are you doing today!",
          "Oi, you interested in ropes now? Well have I got the shop for you!",
          "It ain't much but it's honest work.",
          "Know any good rope jokes? I'm a frayed knot.",
          "A rope and a string got in a race. They tied.",
          "Hello, governor! How are you doing today!",
          "Oi, you interested in ropes now? Well have I got the shop for you!",
          "It ain't much but it's honest work.",
          "Know any good rope jokes? I'm a frayed knot.",
          "A rope and a string got in a race. They tied.",
          
          ],
  items: [
    {
      name: "Normal Rope (50 feet)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(50 feet)",
    },
    {
      name: "Carabiners (Pair, Steel Screw-lock)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Pair, Steel Screw-lock)",
    },
    {
      name: "Clothesline & Camp Lines Kit (Pegs + cord + tensioners)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Pegs + cord + tensioners)",
    },
    {
      name: "Waterproof Knot-Book (Handbook of Practical Knots)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Handbook of Practical Knots)",
    },
    {
      name: "Grappling Hook (Iron, 3-prong)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Iron, 3-prong)",
    },
    {
      name: "Pitons (Set of 10) + Wedge Hammer",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Set of 10) + Wedge Hammer",
    },
    {
      name: "Quick-Deploy Rope Bag (Anti-tangle, fits 50 ft)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Anti-tangle, fits 50 ft)",
    },
    {
      name: "Knotted Throw Line (50 ft, weighted end)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(50 ft, weighted end)",
    },
    {
      name: "Splicing Kit (Fids + waxed twine + needle)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Fids + waxed twine + needle)",
    },
    {
      name: "Rope Ladder (25 ft, wooden rungs)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(25 ft, wooden rungs)",
    },
    {
      name: "Block & Tackle (Haul Kit: 2 pulleys + hooks)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Haul Kit: 2 pulleys + hooks)",
    },
    {
      name: "Silk Rope (25 feet per)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(25 feet per)",
    },
    {
      name: "Cargo Net (Folding, 10 ft x 10 ft)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Folding, 10 ft x 10 ft)",
    },
    {
      name: "Folding Grapnel (Pocket-sized, 4-prong)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(Pocket-sized, 4-prong)",
    },
    {
      name: "Net (100 feet)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(100 feet)",
    },
    {
      name: "Enchanted Climbing Rope (50 feet with hook)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(50 feet with hook)",
    },
    {
      name: "Enchanted Entanglement Rope (25 feet)",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: "(25 feet)",
    },
    {
      name: "Rope of Mending",
      rarity: "Common",
      itemType: "Wondrous Item",
      attunment: false,
      price: 40,
      description: "You can cut this 50-foot coil of hempen rope into any number of smaller pieces, and then use an action to speak a command word and cause the pieces to knit back together. The pieces must be in contact with each other and not otherwise in use. A rope of mending is forever shortened if a section of it is lost or destroyed.",
    },
    {
      name: "Elven Chain",
      rarity: "Rare",
      itemType: "Armor",
      attunment: false,
      price: 1000,
      description: "You gain a +1 bonus to AC while you wear this armor. You are considered proficient with this armor even if you lack proficiency with medium armor.",
    },
    {
      name: "Rope of Entanglement",
      rarity: "Rare",
      itemType: "Wondrous Item",
      attunment: false,
      price: 1000,
      description: `This rope is 30 feet long and weighs 3 pounds. If you hold one end of the rope and use an action to speak its command word, the other end darts forward to entangle a creature you can see within 20 feet of you. The target must succeed on a DC 15 Dexterity saving throw or become restrained.
You can release the creature by using a bonus action to speak a second command word. A target restrained by the rope can use an action to make a DC 15 Strength or Dexterity check (target's choice). On a success, the creature is no longer restrained by the rope.
The rope has AC 20 and 20 hit points. It regains 1 hit point every 5 minutes as long as it has at least 1 hit point. If the rope drops to 0 hit points, it is destroyed.`,
    },
    {
      name: "Rope of Climbing",
      rarity: "Uncommon",
      itemType: "Wondrous Item",
      attunment: false,
      price: 250,
      description: `This 60-foot length of silk rope weighs 3 pounds and can hold up to 3,000 pounds. If you hold one end of the rope and use an action to speak the command word, the rope animates. As a bonus action, you can command the other end to move toward a destination you choose. That end moves 10 feet on your turn when you first command it and 10 feet on each of your turns until reaching its destination, up to its maximum length away, or until you tell it to stop. You can also tell the rope to fasten itself securely to an object or to unfasten itself, to knot or unknot itself, or to coil itself for carrying.
If you tell the rope to knot, large knots appear at 1-foot intervals along the rope. While knotted, the rope shortens to a 50-foot length and grants advantage on checks made to climb it.
The rope has AC 20 and 20 hit points. It regains 1 hit point every 5 minutes as long as it has at least 1 hit point. If the rope drops to 0 hit points, it is destroyed.`,
    }
  ],
};
