import { Tribe } from "./types";

export const tribe5: Tribe = {
  name: "Railblade Raiders",
  percentAngry: 10,
  priceVariability: 33,
  insults: [
    "Railblade Raiders is angry at you and don't want to trade with you!",
    "Railblade Raiders found a butterfly and started chasing after it.",
    "Railblade Raiders are starting a union for goblins' rights.",
    "Railblade Raiders just don’t feel like meeting ugly people today.",
    "Railblade Raiders checked your vibe and found it to be rancid. No business for you today.",
    "Railblade Raiders are all in an intense staring contest, so they haven’t looked at the clock in a while.",
    "Railblade Raiders are all waiting for a single package to arrive.",
    "Turns out dementia is contagious, so Railblade Raiders has gone into self-containment, but they forgot the password to get out.",
    "All of Railblade Raiders got sick from a dihydrogen monoxide contest.",
    "Railblade Raiders believe you’re too short.",
    "Railblade Raiders don’t want to serve you because you are not a goblin.",
    "Railblade Raiders are all listening to music in the back and don’t want to leave to deal with you.",
    "There’s a stampede of squirrels that Railblade Raiders are dealing with.",
    "Railblade Raiders has entered an all-you-can-eat Cheeto contest.",
    "Turns out Railblade Raiders is handling a delicate hostage situation with angry squirrels taking over the locomotive engine.",
    "Railblade Raiders are eagerly waiting for the last part to arrive so they can finish their Lego 30,000-piece Death Star.",
    "Railblade Raiders claim it’s break time, again.",
    "Railblade Raiders are supervising the clock. (The clock doesn't have batteries.)",
    "The supervisor is on lunch, and Railblade Raiders don’t work unsupervised.",
    "All of Railblade Raiders has gathered up all their little goblins to hear the tragedy of Darth Plagueis the Wise.",
    "Railblade Raiders have begun planning to steal the Iron Empire’s Declaration of Independence. It's not going so well.",
    "You want Railblade Raiders to work in this economy! Forget about it!",
    "You need to fix the vibe before we even think about bartering with Railblade Raiders! The audacity of some people.",
    "Railblade Raiders has Nummy doing their jobs for them, and Nummy is very stressed. Please be patient.",
    "Railblade Raiders have a sign saying they will be in tomorrow, it looks very dusty with a couple of cobwebs sprawled across it.",
    "Railblade Raiders listened to a song called ‘Afraid’ and now they are too afraid to work.",
    "Someone, not naming names, stole Nom Nom’s lunch, and now Railblade Raiders are all mad about it.",
    "Nom Nom Nom said that the couch would fit through the door, but it didn’t, and now everyone in Railblade Raiders is too tired.",
    "Railblade Raiders’s favorite band released a new song last night, and so they have to listen to it very closely on repeat so we can find Easter eggs.",
    "Railblade Raiders just learned that sharks can’t collect Legos and now we’re too sad to serve you. 😢",
    "Railblade Raiders decided to organize their Skittles by color. Some go missing. They’ve been accusing each other for hours.",
    "Railblade Raiders are having a very in-depth discussion on what kind of cereal everyone would be.",
    "Railblade Raiders went on an impromptu adventure to the Fantasy Dollar Store to make the perfect movie night snack.",
    "Someone decided to share all of their knowledge about insects, and now all of Railblade Raiders wants to know more!",
    "Railblade Raiders went outside to find the softest patch of grass for napping; they can’t find any good glades right now.",
    "A new season of Railblade Raiders’s favorite show just came out! So they are a little busy.",
    "A bunch of squirrels pushed everyone in Railblade Raiders down a flight of stairs, and they collectively decided it would be easier to stay down.",
    "A mysterious litter of kittens has fallen asleep on every single member of Railblade Raiders’s laps. It would be wrong to get up.",
    "Bork Bork, the train’s resident dog tore up Ohm’s favorite stuffed bear. So now Railblade Raiders is having a funeral.",
    "Ivory is having a tea party. So Railblade Raiders has to join in. It would be rude not to.",
    "Railblade Raiders has decided to draw the mythical land of the United States from memory. (If you do this for real, you must post everyone's art on Discord!)",
    "Railblade Raiders got into an argument about who the fastest is, the goblin. (They refuse to settle it with a race.)",
    "Railblade Raiders is having a discussion about apples being in fact oranges. It's not going well.",
    "Railblade Raiders has decided to go ice skating, but it's not winter yet, so they must wait by the pond for it to freeze.",
    "Someone in Railblade Raiders has found an Easter egg. Maybe there are more! So give them a second.",
  ],

  items: [
    {
      name: "Glowy Piece of Paper!",
      price: 6000,
      description: "(Annabel’s Fresh scratch ticket: scratching off this ticket will fully restore all allies including health, spell slots, class features, item cooldowns, and more. This ticket can only be used five times before it dissolves.)",
    },
    {
      name: "Black and Yellow Barrel of Fidget Spinners & Sickness",
      price: 2000,
      description: "(Deals 1d10 true damage if you are within 5ft of this object. I think you're smart enough to figure out why.)",
    },
    {
      name: "Mama Headache Barrel",
      price: 2000,
      description: "(Contains gasoline, triples fire damage after dealt.)",
    },
    {
      name: "Not a Beehive",
      price: 4000,
      description: "(Chainsaw Sword, + STR to hit, deals 1d20 + CON + STR slashing damage.)",
    },
    {
      name: "Lead Belcher",
      price: 4000,
      description: "(A portable cannon that may explode if used too much, +STR to hit, deals 1d12 + CON + STR blunt damage.)",
    },
    {
      name: "Gallon of Americano Blood",
      price: 2000,
      description: "(It's a jug oil, doubles fire damage after dealt.)",
    },
    {
      name: "Whizz Bang",
      price: 2000,
      description: "(Dangerous firework bundle capable of lighting up the night sky in just a flash.)",
    },
    {
      name: "Aaaaggghh!",
      price: 2000,
      description: "(Flash grenade.)",
    },
    {
      name: "Fwoosh!!!",
      price: 4000,
      description: "(Flamethrower, +DEX to hit, deals 1d12 + CON + DEX fire damage. WARNING: WILL NOT WORK IF WET)",
    },
    {
      name: "Nice Dwarf’s Ticket!",
      price: 6000,
      description: "(Pat's get-out-of-jail scratch ticket; scratching this ticket will teleport you back to the last place you slept. It can only be used five times before it dissolves.)",
    },
    {
      name: "Zip Zap Dead",
      price: 4000,
      description: "(Tesla Coil Pistol, +DEX to hit, deals 1d12 + CON + DEX lightning damage. WARNING: WILL NOT WORK IF WET)",
    },
    {
      name: "Stupid Slippery Ticket",
      price: 6000,
      description: "(Keoki's leave-no-trace-behind scratch-off ticket; wipe away your physical evidence of any crime you've committed in the last month. It can only be used five times before it dissolves.)",
    },
    {
      name: "Danger Lady's Meany Stick",
      price: 4000,
      description: "(Witch's Broom, while riding current fly speed is equal to half of your walking speed. It may have a mind of it's own.)",
    },
    {
      name: "Sometime works, sometime don't",
      price: 2000,
      description:
        "(Moonsliver Cloak, This cloak makes the wear invisible while outdoors at night. This cloak doesn't work a week before and after a lunar eclipse.)",
    },
    {
      name: "One cool jacket",
      price: 4000,
      description:
        "(Storm Rider Jacket, AC now 12 gain resistance to lightning and gain a flight speed of 45.)",
    },
    {
      name: "Cat Cape, Cat Cape, your wearing a Cat Cape!",
      price: 6000,
      description:
        "(Cape of Nine Lives, this cape is guarded by a mischievous cat spirit that protects you from death nine times. Whenever you take damage that would otherwise reduce your hit points to 0, you are instead reduced to 1 hit point. If an effect would kill you instantly without causing damage, that effect is nullified. however Each time the cape saves your life, you gradually take on feline traits, such as whiskers, cat ears, and behaviors like the compulsion to knock things over. Casting Greater Restoration or Remove Curse can reverse these changes.)",
    },
  ]
};
