import { Tribe } from "./types";

export const tribe6: Tribe = {
  name: "Loco Lux Motors",
  percentAngry: 95,
  priceVariability: 16,
  insults: [
    "Loco Lux Motors is angry at you and don't want to trade with you!",
    "Loco Lux Motors found a butterfly and started chasing after it.",
    "Loco Lux Motors are starting a union for goblins' rights.",
    "Loco Lux Motors just don’t feel like meeting ugly people today.",
    "Loco Lux Motors checked your vibe and found it to be rancid. No business for you today.",
    "Loco Lux Motors are all in an intense staring contest, so they haven’t looked at the clock in a while.",
    "Loco Lux Motors are all waiting for a single package to arrive.",
    "Turns out dementia is contagious, so Loco Lux Motors has gone into self-containment, but they forgot the password to get out.",
    "All of Loco Lux Motors got sick from a dihydrogen monoxide contest.",
    "Loco Lux Motors believe you’re too short.",
    "Loco Lux Motors don’t want to serve you because you are not a goblin.",
    "Loco Lux Motors are all listening to music in the back and don’t want to leave to deal with you.",
    "There’s a stampede of squirrels that Loco Lux Motors are dealing with.",
    "Loco Lux Motors has entered an all-you-can-eat Cheeto contest.",
    "Turns out Loco Lux Motors is handling a delicate hostage situation with angry squirrels taking over the locomotive engine.",
    "Loco Lux Motors are eagerly waiting for the last part to arrive so they can finish their Lego 30,000-piece Death Star.",
    "Loco Lux Motors claim it’s break time, again.",
    "Loco Lux Motors are supervising the clock. (The clock doesn't have batteries.)",
    "The supervisor is on lunch, and Loco Lux Motors don’t work unsupervised.",
    "All of Loco Lux Motors has gathered up all their little goblins to hear the tragedy of Darth Plagueis the Wise.",
    "Loco Lux Motors have begun planning to steal the Iron Empire’s Declaration of Independence. It's not going so well.",
    "You want Loco Lux Motors to work in this economy! Forget about it!",
    "You need to fix the vibe before we even think about bartering with Loco Lux Motors! The audacity of some people.",
    "Loco Lux Motors has Nummy doing their jobs for them, and Nummy is very stressed. Please be patient.",
    "Loco Lux Motors have a sign saying they will be in tomorrow, it looks very dusty with a couple of cobwebs sprawled across it.",
    "Loco Lux Motors listened to a song called ‘Afraid’ and now they are too afraid to work.",
    "Someone, not naming names, stole Nom Nom’s lunch, and now Loco Lux Motors are all mad about it.",
    "Nom Nom Nom said that the couch would fit through the door, but it didn’t, and now everyone in Loco Lux Motors is too tired.",
    "Loco Lux Motors’s favorite band released a new song last night, and so they have to listen to it very closely on repeat so we can find Easter eggs.",
    "Loco Lux Motors just learned that sharks can’t collect Legos and now we’re too sad to serve you. 😢",
    "Loco Lux Motors decided to organize their Skittles by color. Some go missing. They’ve been accusing each other for hours.",
    "Loco Lux Motors are having a very in-depth discussion on what kind of cereal everyone would be.",
    "Loco Lux Motors went on an impromptu adventure to the Fantasy Dollar Store to make the perfect movie night snack.",
    "Someone decided to share all of their knowledge about insects, and now all of Loco Lux Motors wants to know more!",
    "Loco Lux Motors went outside to find the softest patch of grass for napping; they can’t find any good glades right now.",
    "A new season of Loco Lux Motors’s favorite show just came out! So they are a little busy.",
    "A bunch of squirrels pushed everyone in Loco Lux Motors down a flight of stairs, and they collectively decided it would be easier to stay down.",
    "A mysterious litter of kittens has fallen asleep on every single member of Loco Lux Motors’s laps. It would be wrong to get up.",
    "Bork Bork, the train’s resident dog tore up Ohm’s favorite stuffed bear. So now Loco Lux Motors is having a funeral.",
    "Ivory is having a tea party. So Loco Lux Motors has to join in. It would be rude not to.",
    "Loco Lux Motors has decided to draw the mythical land of the United States from memory. (If you do this for real, you must post everyone's art on Discord!)",
    "Loco Lux Motors got into an argument about who the fastest is, the goblin. (They refuse to settle it with a race.)",
    "Loco Lux Motors is having a discussion about apples being in fact oranges. It's not going well.",
    "Loco Lux Motors has decided to go ice skating, but it's not winter yet, so they must wait by the pond for it to freeze.",
    "Someone in Loco Lux Motors has found an Easter egg. Maybe there are more! So give them a second.",
  ],
  items: [
    
    {
      name: "Wiggly piece of paper!",
      price: 300000,
      description: "(Adel’s copy or clone coupon: after making a purchase, you may trigger this coupon by making an exact copy or clone of the purchase five feet away; this item can only be used once and in official shops.)",
    },
    {
      name: "Bumbling Buggy",
      price: 100000,
      description: "(An extremely loud steampunk based Jeep, more information provided upon purchase.)",
    },
    {
      name: "Killdozer",
      price: 250000,
      description: "(A steampunk based bulldozer with one to many metal spikes, more information provided upon purchase.)",
    },
    {
      name: "Juddering Juggernaut",
      price: 250000,
      description: "(A steampunk based tank that flies backward after every shot, more information provided upon purchase.)",
    },
    {
      name: "War Chug Chug MARK-001",
      price: 300000,
      description: "(A steampunk based all terrain battle train. Possible the very same train the goblins use, more information provided upon purchase.)",
    },
    {
      name: "Rough Rough ta ta",
      price: 100000,
      description: "(A steampunk based motoercycle with sidecar, more information provided upon purchase.)",
    },
    {
      name: "Toot Toot",
      price: 100000,
      description: "(A small steampunk based fishing boat held together with bee's wax, love, & over 40,000 nails. More information provided upon purchase.)",
    },
    {
      name: "Fweeeeeeeeee MARK-058",
      price: 3000000,
      description: "(A steampunk based blimp that leaks helium, more information provided upon purchase.)",
    },
    {
      name: "Claptrap Chopper MARK-777",
      price: 100000,
      description: "(A steampunk based helicopter that sounds like a classroom of children clapping and cheering, more information provided upon purchase.)",
    },
    {
      name: "Shop Stock",
      price: 10000,
      description: "(Own a little bit of stock in a shop of your choice, more information provided upon purchase.)",
    },
  ]
}
