import { Tribe } from "./types";

export const tribeWillsWeapons: Tribe = {
  name: "Will's Weapons",
  owner: "Will Redrockson",
  percentAngry: 0,
  priceVariability: 5,
  insults: [""],
  items: [
    { name: "Blow Dart", description: "1d4, Piercing", price: 5 },
    { name: "Club", description: "1d4, Blunt", price: 5 },
    { name: "Dagger", description: "1d4, Piercing", price: 5 },
    { name: "Light Hammer", description: "1d4, Blunt", price: 5 },
    { name: "Sickle", description: "1d4, Slash", price: 5 },
    { name: "Sling", description: "1d4, Blunt", price: 5 },
    { name: "Whip", description: "1d4, Slash", price: 5 },
    { name: "Hand Axe", description: "1d6, Slash", price: 5 },
    { name: "Hand Crossbow", description: "1d6, Piercing", price: 5 },
    { name: "Javelin", description: "1d6, Piercing", price: 5 },
    { name: "Mace", description: "1d6, Blunt", price: 5 },
    { name: "Quarterstaff", description: "1d6, Blunt", price: 5 },
    { name: "Rapier", description: "1d6, Slash", price: 5 },
    { name: "Scimitar", description: "1d6, Slash", price: 5 },
    { name: "Shortbow", description: "1d6, Piercing", price: 5 },
    { name: "Shortsword", description: "1d6, Slash", price: 5 },
    { name: "Spear", description: "1d6, Piercing", price: 5 },
    { name: "Trident", description: "1d6, Piercing", price: 5 },
    { name: "Battleaxe", description: "1d8, Slash", price: 10 },
    { name: "Flail", description: "1d8, Blunt", price: 10 },
    { name: "Greatclub", description: "1d8, Blunt", price: 10 },
    { name: "Light Crossbow", description: "1d8, Piercing", price: 10 },
    { name: "Longbow", description: "1d8, Piercing", price: 10 },
    { name: "Longsword", description: "1d8, Slash", price: 10 },
    { name: "Morningstar", description: "1d8, Piercing", price: 10 },
    { name: "War Pick", description: "1d8, Piercing", price: 10 },
    { name: "Warhammer", description: "1d8, Blunt", price: 10 },
    { name: "Pike", description: "1d10, Piercing", price: 5 },
    { name: "Heavy Crossbow", description: "1d10, Piercing", price: 5 },
    { name: "Glaive", description: "1d10, Slash", price: 5 },
    { name: "Halberd", description: "1d10, Slash", price: 5 },
    { name: "Greataxe", description: "1d10, Slash", price: 5 },
    { name: "Will's Pistol", description: "1d10, Piercing", price: 5 },
    { name: "Lance", description: "1d12, Piercing", price: 10 },
    { name: "Will's Musket", description: "1d12, Piercing", price: 10 },
    { name: "Will's Knuckle Duster", description: "1d12, Blunt", price: 10 },
    { name: "Greatsword", description: "2d6, Slash", price: 10 },
    { name: "Maul", description: "2d6, Blunt", price: 10 },
    { name: "Will's Taser", description: "2d6, Electric", price: 10 },
  ],
};
