import { Tribe } from "./types";

export const tribe7: Tribe = {
  name: "Council of Condutors",
  percentAngry: 1,
  priceVariability: 30,
  insults: [
    "The Council of Conductors is angry at you and doesn't want to trade with you!",
    "The Council of Conductors found a butterfly and started chasing after it.",
    "The Council of Conductors is starting a union for goblins' rights.",
    "The Council of Conductors just doesn’t feel like meeting ugly people today.",
    "The Council of Conductors checked your vibe and found it to be rancid. No business for you today.",
    "The Council of Conductors is all in an intense staring contest, so they haven’t looked at the clock in a while.",
    "The Council of Conductors is all waiting for a single package to arrive.",
    "Turns out dementia is contagious, so the Council of Conductors has gone into self-containment, but they forgot the password to get out.",
    "All of the Council of Conductors got sick from a dihydrogen monoxide contest.",
    "The Council of Conductors believes you’re too short.",
    "The Council of Conductors doesn’t want to serve you because you are not a goblin.",
    "The Council of Conductors is all listening to music in the back and doesn’t want to leave to deal with you.",
    "There’s a stampede of squirrels that the Council of Conductors is dealing with.",
    "The Council of Conductors has entered an all-you-can-eat Cheeto contest.",
    "Turns out the Council of Conductors is handling a delicate hostage situation with angry squirrels taking over the locomotive engine.",
    "The Council of Conductors is eagerly waiting for the last part to arrive so they can finish their Lego 30,000-piece Death Star.",
    "The Council of Conductors claims it’s break time, again.",
    "The Council of Conductors is supervising the clock. (The clock doesn't have batteries.)",
    "The supervisor is on lunch, and the Council of Conductors doesn’t work unsupervised.",
    "All the Council of Conductors has gathered up all their little goblins to hear the tragedy of Darth Plagueis the Wise.",
    "The Council of Conductors has begun planning to steal the Iron Empire’s Declaration of Independence. It's not going so well.",
    "You want the Council of Conductors to work in this economy! Forget about it!",
    "You need to fix the vibe before we even think about bartering with the Council of Conductors! The audacity of some people.",
    "The Council of Conductors has Nummy doing their jobs for them, and Nummy is very stressed. Please be patient.",
    "The Council of Conductors has a sign saying they will be in tomorrow. It looks very dusty with a couple of cobwebs sprawled across it.",
    "The Council of Conductors listened to a song called ‘Afraid’ and now they are too afraid to work.",
    "Someone, not naming names, stole Nom Nom’s lunch and now the Council of Conductors is all mad about it.",
    "Nom Nom Nom said that the couch would fit through the door, but it didn’t, and now everyone in the Council of Conductors is too tired.",
    "The Council of Conductors’s favorite band released a new song last night and so they have to listen to it very closely on repeat to find Easter eggs.",
    "The Council of Conductors just learned that sharks can’t collect Legos and now we’re too sad to serve you. 😢",
    "The Council of Conductors decided to organize their Skittles by color. Some go missing. They’ve been accusing each other for hours.",
    "The Council of Conductors is having a very in-depth discussion on what kind of cereal everyone would be.",
    "The Council of Conductors went on an impromptu adventure to the Fantasy Dollar Store to make the perfect movie night snack.",
    "Someone decided to share all of their knowledge about insects, and now all the Council of Conductors wants to know more!",
    "The Council of Conductors went outside to find the softest patch of grass for napping; they can’t find any good glades right now.",
    "A new season of the Council of Conductors’s favorite show just came out! So they are a little busy.",
    "A bunch of squirrels pushed everyone in the Council of Conductors down a flight of stairs, and they collectively decided it would be easier to stay down.",
    "A mysterious litter of kittens has fallen asleep on every single member of the Council of Conductors’s laps. It would be wrong to get up.",
    "Bork Bork, the train’s resident dog tore up Ohm’s favorite stuffed bear. So now the Council of Conductors is having a funeral.",
    "Ivory is having a tea party. So the Council of Conductors has to join in. It would be rude not to.",
    "The Council of Conductors has decided to draw the mythical land of the United States from memory. (If you do this for real, you must post everyone's art on Discord!)",
    "The Council of Conductors got into an argument about who the fastest is, the goblin. (They refuse to settle it with a race.)",
    "The Council of Conductors is having a discussion about apples being in fact oranges. It's not going well.",
    "The Council of Conductors has decided to go ice skating, but it's not winter yet, so they must wait by the pond for it to freeze.",
    "Someone in the Council of Conductors has found an Easter egg. Maybe there are more! So give them a second."
],
  items: [
    
    {
      name: "Tiny Duck Crown.",
      price: 3000,
      description: "(While playing an instrument roll 3d100 that is how many rubber ducks fall out of your pockets or real ducks appear. They will disapear is you stop playing.)",
    },
    {
      name: "Quick Swap Ring.",
      price: 10000,
      description: "(Swap places with someone within 200 ft once per day.)",
    },
    {
      name: "Necklace of Shatter ages.",
      price: 2500,
      description: "(Spinning the gem on the Necklace will allow the user to see past events that happenend near by.)",
    },
    {
      name: "Gateway Amulet",
      price: 2500,
      description: "(Create a portal that lasts 5 mins to someone you know who is also wearing a Gateway Amulet, can be used twice per long rest.)",
    },
    {
      name: "Insatiable Tome",
      price: 3000,
      description: "(This book eats other books, ask the book a question and it will respond if it ate a book that has the answer you're looking for.)",
    },
    {
      name: "Orb of Summoning",
      price: 1000,
      description: "(Prefrome a ten minute ritual to bring forth... something? What's your alignment again?)",
    },
    {
      name: "Adel's Old Monster Journal",
      price: 1000,
      description: "(A journal explaining a lot of monsters Adel encountered on her past adventures.)",
    },
    {
      name: "Odin's Glass Eye",
      price: 3000,
      description: "(Warning, your charater has to remove one of their funtioning eyes for this item to work! You can now summon two ravens of which you can see through there eyes, however if one of the ravens dies so does the other. Ravens can be summoned once per long rest.)",
    },
    {
      name: "Pat's Homemade Cottage Chest",
      price: 1000,
      description: "(Placing this small box on the ground and opening it will allow you to enter a tiny dimension place that is akin to being inside a real cabin. The chest's weight double for each living creature in their.)",
    },
    {
      name: "Omega Skeleton Key",
      price: 1000000,
      description: "(Can unlock any door if the door has a lock. It does not work if it's any other kind of lock.)",
    },
    {
      name: "Goblin Warlord's Crown",
      price: 2000000,
      description: "(All goblins within ten miles of the wearer have to obey the obey their commands, if they can hear and understand it. Only three commands can be active at any given time.)",
    },
    {
      name: "Even more terrible cards",
      price: 1000000,
      description: "(The deck of many fates.)",
    },
    {
      name: "Some terrible cards",
      price: 1000000,
      description: "(The deck of many things.)",
    },
    {
      name: "Skill training",
      price: 9000,
      description: "(gain proficiency in a skill of your choosing if you already have proficiency in that skill it becomes expertise.)",
    },
    {
      name: "Used Bag of Holding",
      price: 1000,
      description: "(This is a bag of holding, however some items you withdraw may have a bit of glitter on them. Not you may not put living beings in here.)",
    },   
    {
      name: "A really handy Hat",
      price: 1000000,
      description: "(Whenever you reach into this hat you one in three chance of withdrawing a useful item, a detrimental item, or a clue for your current quest.)",
    },   
    {
      name: "Ring of Replenishing Snowballs",
      price: 3,
      description: "(Create and throw up to five harmless snowballs a day, they always hit.)",
    },   
  ]
}
