import { Tribe } from "./types";

export const tribe2: Tribe = {
  name: "Grubcar Clan",
  percentAngry: 20,
  priceVariability: 81,
  insults: [
    "Grubcar Clan is angry at you and don't want to trade with you!",
    "Grubcar Clan found a butterfly and started chasing after it.",
    "Grubcar Clan are starting a union for goblins' rights.",
    "Grubcar Clan just don’t feel like meeting ugly people today.",
    "Grubcar Clan checked your vibe and found it to be rancid. No business for you today.",
    "Grubcar Clan are all in an intense staring contest, so they haven’t looked at the clock in a while.",
    "Grubcar Clan are all waiting for a single package to arrive.",
    "Turns out dementia is contagious, so Grubcar Clan has gone into self-containment, but they forgot the password to get out.",
    "All of Grubcar Clan got sick from a dihydrogen monoxide contest.",
    "Grubcar Clan believe you’re too short.",
    "Grubcar Clan don’t want to serve you because you are not a goblin.",
    "Grubcar Clan are all listening to music in the back and don’t want to leave to deal with you.",
    "There’s a stampede of squirrels that Grubcar Clan are dealing with.",
    "Grubcar Clan has entered an all-you-can-eat Cheeto contest.",
    "Turns out Grubcar Clan is handling a delicate hostage situation with angry squirrels taking over the locomotive engine.",
    "Grubcar Clan are eagerly waiting for the last part to arrive so they can finish their Lego 30,000-piece Death Star.",
    "Grubcar Clan claim it’s break time, again.",
    "Grubcar Clan are supervising the clock. (The clock doesn't have batteries.)",
    "The supervisor is on lunch, and Grubcar Clan don’t work unsupervised.",
    "All of Grubcar Clan has gathered up all their little goblins to hear the tragedy of Darth Plagueis the Wise.",
    "Grubcar Clan have begun planning to steal the Iron Empire’s Declaration of Independence. It's not going so well.",
    "You want Grubcar Clan to work in this economy! Forget about it!",
    "You need to fix the vibe before we even think about bartering with Grubcar Clan! The audacity of some people.",
    "Grubcar Clan has Nummy doing their jobs for them, and Nummy is very stressed. Please be patient.",
    "Grubcar Clan have a sign saying they will be in tomorrow, it looks very dusty with a couple of cobwebs sprawled across it.",
    "Grubcar Clan listened to a song called ‘Afraid’ and now they are too afraid to work.",
    "Someone, not naming names, stole Nom Nom’s lunch, and now Grubcar Clan are all mad about it.",
    "Nom Nom Nom said that the couch would fit through the door, but it didn’t, and now everyone in Grubcar Clan is too tired.",
    "Grubcar Clan’s favorite band released a new song last night, and so they have to listen to it very closely on repeat so we can find Easter eggs.",
    "Grubcar Clan just learned that sharks can’t collect Legos and now we’re too sad to serve you. 😢",
    "Grubcar Clan decided to organize their Skittles by color. Some go missing. They’ve been accusing each other for hours.",
    "Grubcar Clan are having a very in-depth discussion on what kind of cereal everyone would be.",
    "Grubcar Clan went on an impromptu adventure to the Fantasy Dollar Store to make the perfect movie night snack.",
    "Someone decided to share all of their knowledge about insects, and now all of Grubcar Clan wants to know more!",
    "Grubcar Clan went outside to find the softest patch of grass for napping; they can’t find any good glades right now.",
    "A new season of Grubcar Clan’s favorite show just came out! So they are a little busy.",
    "A bunch of squirrels pushed everyone in Grubcar Clan down a flight of stairs, and they collectively decided it would be easier to stay down.",
    "A mysterious litter of kittens has fallen asleep on every single member of Grubcar Clan’s laps. It would be wrong to get up.",
    "Bork Bork, the train’s resident dog tore up Ohm’s favorite stuffed bear. So now Grubcar Clan is having a funeral.",
    "Ivory is having a tea party. So Grubcar Clan has to join in. It would be rude not to.",
    "Grubcar Clan has decided to draw the mythical land of the United States from memory. (If you do this for real, you must post everyone's art on Discord!)",
    "Grubcar Clan got into an argument about who the fastest is, the goblin. (They refuse to settle it with a race.)",
    "Grubcar Clan is having a discussion about apples being in fact oranges. It's not going well.",
    "Grubcar Clan has decided to go ice skating, but it's not winter yet, so they must wait by the pond for it to freeze.",
    "Someone in Grubcar Clan has found an Easter egg. Maybe there are more! So give them a second.",
  ],

  items: [
    {
      name: "Waste of Good Napkin",
      price: 110,
      description: "(A coupon that offers 25% off your next purchase anywhere; valid for one use only.)",
    },
    {
      name: "Snack?",
      price: 35,
      description: "(Some thrown-out food found in a dumpster, heals 1d4.)",
    },
    {
      name: "Goblin Hand Sanitizer",
      price: 35,
      description: "(An unopened jar of peanut butter, heals 2d6.)",
    },
    {
      name: "Dino!",
      price: 110,
      description: "(Dinosaur nuggets with your choice of dipping sauce, heals 6d6.)",
    },
    {
      name: "Garbage Crown!",
      price: 75,
      description: "(A Burger King crown that will stay on your head until you take it off.)",
    },
    {
      name: "Disappointment",
      price: 75,
      description: "(A batch of perfectly baked cookies, but the goblins don't have any milk to go with them. Each cookie heals for 5)",
    },
    {
      name: "Soup?",
      price: 35,
      description: "(A soggy bowl of cereal, heals 1d6.)",
    },
    {
      name: "Docter Be GONE!",
      price: 110,
      description: "(A shiny red apple the regenerates itself after half of it is gone, each bite heal for 1.)",
    },
    {
      name: "Hobo Gum",
      price: 35,
      description: "(A rock, small enough to chew on.)",
    },
    {
      name: "Terrible Seasonal Cookie Thief",
      price: 75,
      description: "(Santa's hat.)",
    },
    {
      name: "The One True Enemy",
      price: 75,
      description: "(A bar of soap with a bite taken out of it?)",
    },
    {
      name: "Last Week's Fish Trip",
      price: 110,
      description: "(Six left boots, three fish, one fishing pole with a pair of pants on the hook, and a tombstone.)",
    },
    {
      name: "Holly's Grail",
      price: 110,
      description: "(A fresh Costco rotisserie chicken, probably stolen from a person named Holly because her receipt is still in the bag. Heal's for 6d12)",
    },
    {
      name: "No no no I'm your brother! Remeber we used to luagh and play down by the river and mom would always make us a sandwitch when we came in side covered in mud!",
      price: 35,
      description:
        "(Potion of Forget-Me-Not, After drinking this potion you will be forgotten by everyone who knows you. Unless they have psionic/psychic immune or resistance.)",
    },
    {
      name: "Liquid Golden Cat Eyes",
      price: 75,
      description:
        "(A semi permanent potion of Dark vision up to 120 feet. However your after drinking and while in darkness your eyes shift from their original color to a golden yellow and your pupils stretch, giving them a slitted, cat-like appearance.)",
    },
    {
      name: "You really hurt my feelings, why would you do that!",
      price: 110,
      description:
        "(Liar's Breath, After drinking this potion, you gain a +10 to all Deception rolls, however you are also unable to answer truthfully to any question. The effects of this potion last for 5 hours.)",
    },
  ],
};
