export function createGoblinExcuses(name: string): string[] {
  return [
    `${name} are angry at you and don't want to trade with you!`,
    `${name} found a butterfly and started chasing after it.`,
    `${name} are starting a union for goblin rights.`,
    `${name} just don’t feel like meeting ugly people today.`,
    `${name} checked your vibe and found it rancid. No business for you today.`,
    `${name} are all in an intense staring contest, so they haven’t looked at the clock in a while.`,
    `${name} are all waiting for a single package to arrive.`,
    `Turns out dementia is contagious, so ${name} have gone into self-isolation, but they forgot the password to get out.`,
    `All of ${name} got sick after a dihydrogen monoxide contest.`,
    `${name} believe you’re too short.`,
    `${name} don’t want to serve you because you are not a goblin.`,
    `${name} are all listening to music in the back and don’t want to come out to deal with you.`,
    `There’s a stampede of squirrels that ${name} are dealing with.`,
    `${name} have entered an all-you-can-eat Cheeto contest.`,
    `It turns out ${name} are handling a delicate hostage situation with angry squirrels taking over the locomotive engine.`,
    `${name} are eagerly waiting for the last part to arrive so they can finish their Lego 30,000-piece Death Star.`,
    `${name} claim it’s break time again.`,
    `${name} are supervising the clock. (The clock doesn't have batteries.)`,
    `The supervisor is on lunch, and ${name} don’t work unsupervised.`,
    `All of ${name} have gathered up their little goblins to hear the tragedy of Darth Plagueis the Wise.`,
    `${name} have begun planning to steal the Iron Empire’s Declaration of Independence. It's not going so well.`,
    `You want ${name} to work in this economy! Forget about it!`,
    `You need to fix the vibe before we even think about bartering with ${name}! The audacity of some people.`,
    `${name} have Nummy doing their jobs for them, and Nummy is very stressed. Please be patient.`,
    `${name} have a sign saying they will be in tomorrow. It looks very dusty, with a couple of cobwebs sprawled across it.`,
    `${name} listened to a song called ‘Afraid’ and now they are too afraid to work.`,
    `Someone, not naming names, stole Nom Nom’s lunch, and now ${name} are all mad about it.`,
    `Nom Nom Nom said that the couch would fit through the door, but it didn’t, and now everyone in ${name} is too tired.`,
    `${name}’s favorite band released a new song last night, so they have to listen to it very closely on repeat to find every Easter egg.`,
    `${name} just learned that sharks can’t collect Legos, and now we’re too sad to serve you. 😢`,
    `${name} decided to organize their Skittles by color. Some went missing. They’ve been accusing each other for hours.`,
    `${name} are having a very in-depth discussion on what kind of cereal everyone would be.`,
    `${name} went on an impromptu adventure to the Fantasy Dollar Store to make the perfect movie night snack.`,
    `Someone decided to share all of their knowledge about insects, and now everyone in ${name} wants to know more!`,
    `${name} went outside to find the softest patch of grass for napping; they can’t find any good glades right now.`,
    `A new season of ${name}’s favorite show just came out, so they are a little busy.`,
    `A bunch of squirrels pushed everyone in ${name} down a flight of stairs, and they collectively decided it would be easier to stay down.`,
    `A mysterious litter of kittens has fallen asleep on every single member of ${name}. It would be wrong to get up.`,
    `Bork Bork, the train’s resident dog, tore up Ohm’s favorite stuffed bear, so now ${name} are having a funeral.`,
    `Ivory is having a tea party, so ${name} have to join in. It would be rude not to.`,
    `${name} have decided to draw the mythical land of the United States from memory. (If you do this for real, you must post everyone's art on Discord!)`,
    `${name} got into an argument about which goblin is the fastest. (They refuse to settle it with a race.)`,
    `${name} are having a discussion about apples actually being oranges. It's not going well.`,
    `${name} has decided to go ice skating, but it's not winter yet, so they must wait by the pond for it to freeze.`,
    `Someone in ${name} has found an Easter egg. Maybe there are more! Give them a second.`,
  ];
}

export const blackMarketInsults: string[] = [
  "Sellers don’t meet buyers. That’s the rule—capisce?",
  "The shop’s mobile, off the grid. I ain’t takin’ you there.",
  "They work in shadows, not with tourists. Don’t ask again.",
  "No faces, no follow-ups. That’s how they stay alive.",
  "It’s too hot right now. Shop’s bein’ watched.",
  "You don’t got the creds. Don’t waste my time.",
  "They skipped town after someone got sloppy. Didn’t end pretty.",
  "I can’t show ya what ain’t safe to see. That’s their call.",
  "Last guy I brought? Curiosity cost 'em. You wanna be next?",
  "Some doors stay shut for a reason. This one’s welded.",
  "Too many eyes in the alley today. Step off.",
  "Shop’s locked down—heat’s too loud lately.",
  "They don’t deal with strangers. You ain’t got a rep.",
  "It’s invite-only. You ain’t on the list.",
  "I ain’t takin’ you where you don’t belong.",
  "Access needs guarantees. I ain’t puttin’ my neck on the line for you.",
  "You’re on the outside. Best stay there.",
  "Seller’s jumpy. You show up, we both got problems.",
  "This route’s closed ‘cause they said so. I don’t argue.",
  "Rules ain’t mine—I just enforce ‘em. You? You ain't gettin’ in.",
  "We ain’t goin’. Guards are makin’ rounds. You wanna get pinched?",
];
