import { Tribe } from "./types";

export const tribe7: Tribe = {
  name: "Council of Conductors",
  percentAngry: 1,
  priceVariability: 30,
  insults: [
    "The Council of Conductors is angry at you and doesn't want to trade with you!",
    "The Council of Conductors found a butterfly and started chasing after it.",
    "The Council of Conductors is starting a union for goblins' rights.",
    "The Council of Conductors just doesn’t feel like meeting ugly people today.",
    "The Council of Conductors checked your vibe and found it to be rancid. No business for you today.",
    "The Council of Conductors is all in an intense staring contest, so they haven’t looked at the clock in a while.",
    "The Council of Conductors is all waiting for a single package to arrive.",
    "Turns out dementia is contagious, so the Council of Conductors has gone into self-containment, but they forgot the password to get out.",
    "All of the Council of Conductors got sick from a dihydrogen monoxide contest.",
    "The Council of Conductors believes you’re too short.",
    "The Council of Conductors doesn’t want to serve you because you are not a goblin.",
    "The Council of Conductors is all listening to music in the back and doesn’t want to leave to deal with you.",
    "There’s a stampede of squirrels that the Council of Conductors is dealing with.",
    "The Council of Conductors has entered an all-you-can-eat Cheeto contest.",
    "Turns out the Council of Conductors is handling a delicate hostage situation with angry squirrels taking over the locomotive engine.",
    "The Council of Conductors is eagerly waiting for the last part to arrive so they can finish their Lego 30,000-piece Death Star.",
    "The Council of Conductors claims it’s break time, again.",
    "The Council of Conductors is supervising the clock. (The clock doesn't have batteries.)",
    "The supervisor is on lunch, and the Council of Conductors doesn’t work unsupervised.",
    "All the Council of Conductors have gathered up all their little goblins to hear the tragedy of Darth Plagueis the Wise.",
    "The Council of Conductors has begun planning to steal the Iron Empire’s Declaration of Independence. It's not going so well.",
    "You want the Council of Conductors to work in this economy! Forget about it!",
    "You need to fix the vibe before we even think about bartering with the Council of Conductors! The audacity of some people.",
    "The Council of Conductors has Nummy doing their jobs for them, and Nummy is very stressed. Please be patient.",
    "The Council of Conductors has a sign saying they will be in tomorrow. It looks very dusty with a couple of cobwebs sprawled across it.",
    "The Council of Conductors listened to a song called ‘Afraid’ and now they are too afraid to work.",
    "Someone, not naming names, stole Nom Nom’s lunch and now the Council of Conductors is all mad about it.",
    "Nom Nom Nom said that the couch would fit through the door, but it didn’t, and now everyone in the Council of Conductors is too tired.",
    "The Council of Conductors’s favorite band released a new song last night and so they have to listen to it very closely on repeat to find Easter eggs.",
    "The Council of Conductors just learned that sharks can’t collect Legos and now we’re too sad to serve you. 😢",
    "The Council of Conductors decided to organize their Skittles by color. Some go missing. They’ve been accusing each other for hours.",
    "The Council of Conductors is having a very in-depth discussion on what kind of cereal everyone would be.",
    "The Council of Conductors went on an impromptu adventure to the Fantasy Dollar Store to make the perfect movie night snack.",
    "Someone decided to share all of their knowledge about insects, and now all the Council of Conductors wants to know more!",
    "The Council of Conductors went outside to find the softest patch of grass for napping; they can’t find any good glades right now.",
    "A new season of the Council of Conductors’s favorite show just came out! So they are a little busy.",
    "A bunch of squirrels pushed everyone in the Council of Conductors down a flight of stairs, and they collectively decided it would be easier to stay down.",
    "A mysterious litter of kittens has fallen asleep on every single member of the Council of Conductors’s laps. It would be wrong to get up.",
    "Bork Bork, the train’s resident dog tore up Ohm’s favorite stuffed bear. So now the Council of Conductors is having a funeral.",
    "Ivory is having a tea party. So the Council of Conductors has to join in. It would be rude not to.",
    "The Council of Conductors has decided to draw the mythical land of the United States from memory. (If you do this for real, you must post everyone's art on Discord!)",
    "The Council of Conductors got into an argument about who the fastest is, the goblin. (They refuse to settle it with a race.)",
    "The Council of Conductors is having a discussion about apples being in fact oranges. It's not going well.",
    "The Council of Conductors has decided to go ice skating, but it's not winter yet, so they must wait by the pond for it to freeze.",
    "Someone in the Council of Conductors has found an Easter egg. Maybe there are more! So give them a second."
  ],
  items: [
    {
      name: "OH NO THERE BACK AGAIN GET THE BREAD, GET THE BREADDDD!!!!",
      price: 3000,
      description: "(Tiny Duck Crown, While playing an instrument roll 3d100 that is how many rubber ducks fall out of your pockets or real ducks appear. They will disappear if you stop playing.)",
    },
    {
      name: "Cut in line, Na na a boo bo.",
      price: 10000,
      description: "(Quick Swap Ring, Swap places with someone within 200 ft once per day.)",
    },
    {
      name: "Neck rope of ghost summoning",
      price: 2500,
      description: "(Necklace of Shattered Ages, Spinning the gem on the Necklace will allow the user to see past events that happened nearby.)",
    },
    {
      name: "Derpy lucky charm",
      price: 2500,
      description: "(Gateway Amulet, Create a portal that lasts 5 mins to someone you know who is also wearing a Gateway Amulet, can be used twice per long rest.)",
    },
    {
      name: "Peabrain page holder ate, my cookbook!",
      price: 3000,
      description: "(Insatiable Tome, This book eats other books, ask the book a question and it will respond if it ate a book that has the answer you're looking for. Also contains some goblin cooking recipes.)",
    },
    {
      name: "Sphere of bringing fun friends.",
      price: 1000,
      description: "(Orb of Summoning, Perform a ten-minute ritual to bring forth... something? What's your alignment again?)",
    },
    {
      name: "Nice elf lady's book.",
      price: 1000,
      description: "(Adel's Old Monster Journal, A journal explaining a lot of monsters Adel encountered on her past adventures.)",
    },
    {
      name: "Eeew, gross I don't want to touch it.",
      price: 3000,
      description: "(Odin's Glass Eye, Warning, your character has to remove one of their functioning eyes for this item to work! You can now summon two ravens of which you can see through their eyes, however if one of the ravens dies so does the other. Ravens can be summoned once per long rest.)",
    },
    {
      name: "Kind Dwarf's odd box.",
      price: 1000,
      description: "(Pat's Homemade Cottage Chest, Placing this small box on the ground will allow it to open, granting you access to a tiny, cozy-dimension place akin to being inside an authentic cabin. The chest can't be moved if there's a living being inside, but the chest can be destroyed. Where upon any living inside the chest being will be teleported to a safe place from the destruction.)",
    },
    {
      name: "Creepy bone hand, good for picking ear tho.",
      price: 1000000,
      description: "(Omega Skeleton Key, Can unlock any door if the door has a lock. It does not work if it's any other kind of lock.)",
    },
    {
      name: "The dishonorable & malicious tiara of Solanine the goblin queen.",
      price: 9000000,
      description: "(Goblin Warlord's Crown, All goblins within ten miles of the wearer have to obey their commands, if they can hear and understand it. Only three commands can be active at any given time with the oldest command being erased.)",
    },
    {
      name: "Some terrible cards.",
      price: 1000000,
      description: "(It's the Deck of Many Things & Many Fates, but the goblins may have shuffled them together and aren't too willing to go back and sort it out.)",
    },
    {
      name: "The forbidden tissue.",
      price: 300000,
      description: "(Keoki's All or Nothing Scratch ticket: after making a purchase, you may trigger this scratch ticket where you flip a coin. If heads the purchase automatically upgrades to ultimate version of it's self becoming an artifact item. If tails both the scratch ticket and purchase disappear never to be seen again.)",
    },
    {
      name: "Hands-on goblin learning, they may rough you up a bit tho.",
      price: 90,
      description: "(Skill training, gain proficiency in a skill of your choosing if you already have proficiency in that skill it becomes expertise.)",
    },
    {
      name: "Not the kidnap- I mean a normal bag.",
      price: 1000,
      description: "(Used Bag of Holding, This is a bag of holding however some items you withdraw may have a bit of glitter on them. It may have some other items in there.)",
    },
    {
      name: "A really handy Hat",
      price: 100000,
      description: "(Wander's Hat, Whenever you reach into this hat you one in three chance of withdrawing a useful item, a detrimental item, or a clue for your current quest.)",
    },
    {
      name: "SNOW BALL FIGHT! But it's the middle of summer? SNOW BALL FIGHT!",
      price: 3,
      description: "(Ring of Replenishing Snowballs, Create and throw up to five harmless snowballs a day, they always hit.)",
    },
  ]
}
